import { useCallback, useEffect, useMemo, useState } from "react";
import { API_BASE_URL, apiFetch } from "../src/services/apiClient";
import ReceiptModal from "../components/ReceiptModal";

const statusOptions = ["pending", "accepted", "processing", "picked_up", "delivered", "rejected", "cancelled"];

const formatDateTime = (dateValue) => {
  if (!dateValue) return "-";
  const date = new Date(dateValue);
  if (Number.isNaN(date.getTime())) return "-";
  return date.toLocaleString();
};

const formatCurrency = (amount) => `N${Number(amount || 0).toLocaleString()}`;

const businessTypeLabel = (type) => (type === "shop" ? "Shop" : "Restaurant");

const toPublicAssetUrl = (assetPath = "") => {
  if (!assetPath) return "";
  if (assetPath.startsWith("http")) return assetPath;
  const base = API_BASE_URL.replace(/\/api\/?$/i, "");
  return `${base}${assetPath.startsWith("/") ? "" : "/"}${assetPath}`;
};

const sanitizeForPdf = (value) =>
  String(value ?? "")
    .replace(/\r/g, "")
    .replace(/[^\x20-\x7E]/g, "?");

const escapePdfText = (value) =>
  sanitizeForPdf(value)
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");

const wrapText = (text, maxChars = 92) => {
  const value = sanitizeForPdf(text).trim();
  if (!value) return [""];

  const words = value.split(/\s+/);
  const lines = [];
  let current = "";

  words.forEach((word) => {
    if (!current) {
      current = word;
      return;
    }

    if (`${current} ${word}`.length <= maxChars) {
      current = `${current} ${word}`;
    } else {
      lines.push(current);
      current = word;
    }
  });

  if (current) lines.push(current);
  return lines.length ? lines : [value];
};

const buildOrderPdfBlob = (order) => {
  const businesses = (order.businesses || []).map((business) => business.name);
  const itemLines = (order.items || []).map((item, index) => {
    const source = item.possibleBusinesses?.length
      ? item.possibleBusinesses.map((business) => business.name).join(", ")
      : "Unknown";
    return `${index + 1}. ${item.name} | Qty: ${item.qty} | Unit: ${formatCurrency(item.price)} | Line: ${formatCurrency(item.price * item.qty)} | Source: ${source}`;
  });

  const lines = [
    "HamarsRide Order Rider Sheet",
    `Order ID: ${order.id || "-"}`,
    `Date: ${formatDateTime(order.createdAt)}`,
    `Order Status: ${order.rejectionReason ? "rejected" : order.status || "pending"}`,
    `Payment Status: ${order.latestPayment?.status || "no payment"}`,
    "",
    "Customer Details",
    `Name: ${order.user?.name || "-"}`,
    `Phone: ${order.user?.phone || "-"}`,
    `Alt Phone: ${order.user?.altPhone || "-"}`,
    `Email: ${order.user?.email || "-"}`,
    "",
    "Delivery Details",
    `Address: ${order.address || "-"}`,
    `Instruction: ${order.instruction || "-"}`,
    "",
    "Businesses",
    businesses.length ? businesses.map((name, index) => `${index + 1}. ${name}`).join(" | ") : "No source business matched.",
    "",
    "Items",
    ...(itemLines.length ? itemLines : ["No items found."]),
    "",
    `Subtotal: ${formatCurrency(order.subtotal)}`,
    `Delivery Fee: ${formatCurrency(order.deliveryFee)}`,
    `Total: ${formatCurrency(order.total)}`,
    "",
    "Generated by HamarsRide Admin.",
  ];

  const printableLines = lines.flatMap((line) => wrapText(line));
  const linesPerPage = 48;
  const pages = [];
  for (let i = 0; i < printableLines.length; i += linesPerPage) {
    pages.push(printableLines.slice(i, i + linesPerPage));
  }
  if (pages.length === 0) pages.push(["Order"]);

  const encoder = new TextEncoder();
  const getByteLength = (value) => encoder.encode(value).length;
  const objects = {};

  const catalogId = 1;
  const pagesId = 2;
  const fontId = 3;
  let nextObjectId = 4;
  const pageObjectIds = [];

  pages.forEach((pageLines) => {
    const contentId = nextObjectId++;
    const pageId = nextObjectId++;

    const textCommands = pageLines
      .map((line, index) =>
        index === 0 ? `(${escapePdfText(line)}) Tj` : `T* (${escapePdfText(line)}) Tj`
      )
      .join("\n");

    const contentStream = `BT
/F1 11 Tf
14 TL
40 800 Td
${textCommands}
ET`;

    objects[contentId] = `<< /Length ${getByteLength(contentStream)} >>
stream
${contentStream}
endstream`;
    objects[pageId] = `<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${contentId} 0 R >>`;
    pageObjectIds.push(pageId);
  });

  objects[fontId] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";
  objects[pagesId] = `<< /Type /Pages /Count ${pageObjectIds.length} /Kids [${pageObjectIds
    .map((id) => `${id} 0 R`)
    .join(" ")}] >>`;
  objects[catalogId] = `<< /Type /Catalog /Pages ${pagesId} 0 R >>`;

  const maxObjectId = nextObjectId - 1;
  const offsets = new Array(maxObjectId + 1).fill(0);
  const chunks = [];
  let cursor = 0;

  const pushChunk = (value) => {
    chunks.push(value);
    cursor += getByteLength(value);
  };

  pushChunk("%PDF-1.4\n");
  for (let id = 1; id <= maxObjectId; id += 1) {
    offsets[id] = cursor;
    pushChunk(`${id} 0 obj\n${objects[id]}\nendobj\n`);
  }

  const xrefPosition = cursor;
  pushChunk(`xref\n0 ${maxObjectId + 1}\n`);
  pushChunk("0000000000 65535 f \n");
  for (let id = 1; id <= maxObjectId; id += 1) {
    pushChunk(`${String(offsets[id]).padStart(10, "0")} 00000 n \n`);
  }
  pushChunk(`trailer\n<< /Size ${maxObjectId + 1} /Root ${catalogId} 0 R >>\nstartxref\n${xrefPosition}\n%%EOF`);

  return new Blob(chunks, { type: "application/pdf" });
};

export default function AdminOrders() {
  const [orders, setOrders] = useState([]);
  const [statusFilter, setStatusFilter] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [generatingReceiptId, setGeneratingReceiptId] = useState("");
  const [viewingReceiptId, setViewingReceiptId] = useState("");
  const [selectedReceipt, setSelectedReceipt] = useState(null);
  const [rejectingOrder, setRejectingOrder] = useState(null);
  const [rejectionReason, setRejectionReason] = useState("");

  const loadOrders = useCallback(async () => {
    try {
      setLoading(true);
      setError("");
      const path = statusFilter ? `/admin/orders?status=${statusFilter}` : "/admin/orders";
      const payload = await apiFetch(path);
      setOrders(payload.orders || []);
    } catch (err) {
      setError(err.message || "Failed to load orders.");
    } finally {
      setLoading(false);
    }
  }, [statusFilter]);

  useEffect(() => {
    loadOrders();
  }, [loadOrders]);

  const statusBadge = useMemo(
    () => ({
      pending: "bg-gray-100 text-gray-700",
      accepted: "bg-blue-100 text-blue-700",
      processing: "bg-orange-100 text-orange-700",
      picked_up: "bg-amber-100 text-amber-700",
      delivered: "bg-green-100 text-green-700",
      rejected: "bg-red-100 text-red-700",
      cancelled: "bg-red-100 text-red-700",
    }),
    []
  );

  const paymentBadge = useMemo(
    () => ({
      submitted: "bg-amber-100 text-amber-700",
      verified: "bg-green-100 text-green-700",
      rejected: "bg-red-100 text-red-700",
    }),
    []
  );

  const updateOrderStatus = async (orderId, status) => {
    if (status === "rejected") {
      setRejectingOrder(orders.find((item) => item.id === orderId) || { id: orderId });
      setRejectionReason("");
      return;
    }

    const ok = window.confirm(`Change order ${orderId} to ${status.replace("_", " ")}?`);
    if (!ok) return;

    try {
      await apiFetch(`/admin/orders/${orderId}/status`, {
        method: "PATCH",
        body: JSON.stringify({ status }),
      });
      loadOrders();
    } catch (err) {
      setError(err.message || "Failed to update order.");
    }
  };

  const submitRejection = async () => {
    if (!rejectingOrder?.id) return;

    const reason = rejectionReason.trim();
    if (!reason) {
      setError("Please provide a rejection reason.");
      return;
    }

    try {
      await apiFetch(`/admin/orders/${rejectingOrder.id}/status`, {
        method: "PATCH",
        body: JSON.stringify({ status: "rejected", rejectionReason: reason }),
      });
      setRejectingOrder(null);
      setRejectionReason("");
      loadOrders();
    } catch (err) {
      setError(err.message || "Failed to reject order.");
    }
  };

  const generateReceipt = async (orderId) => {
    const ok = window.confirm(`Generate receipt for order ${orderId}?`);
    if (!ok) return;

    try {
      setGeneratingReceiptId(orderId);
      const payload = await apiFetch("/receipts", {
        method: "POST",
        body: JSON.stringify({ orderId }),
      });
      setSelectedReceipt(payload.receipt || null);
      loadOrders();
    } catch (err) {
      setError(err.message || "Failed to generate receipt.");
    } finally {
      setGeneratingReceiptId("");
    }
  };

  const viewReceipt = async (order) => {
    if (order.latestReceipt) {
      setSelectedReceipt(order.latestReceipt);
      return;
    }

    try {
      setViewingReceiptId(order.id);
      const payload = await apiFetch(`/receipts/order/${order.id}`);
      setSelectedReceipt(payload.receipt || null);
    } catch (err) {
      setError(err.message || "Failed to load receipt.");
    } finally {
      setViewingReceiptId("");
    }
  };

  const downloadOrderPdf = (order) => {
    const blob = buildOrderPdfBlob(order);
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `order-${order.id || "details"}-rider-sheet.pdf`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  };

  const renderSourceBusinesses = (order) => {
    const businesses = order.businesses || [];
    if (!businesses.length) {
      return <span className="text-gray-500">No source business matched.</span>;
    }

    return (
      <div className="flex flex-wrap gap-2">
        {businesses.map((business) => (
          <span
            key={business.id}
            className="rounded-full border border-gray-200 bg-gray-50 px-3 py-1 text-xs font-medium text-gray-700"
          >
            {business.name} ({businessTypeLabel(business.type)})
          </span>
        ))}
      </div>
    );
  };

  return (
    <section className="space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-gray-100 bg-white p-5 shadow-sm sm:p-6">
        <h2 className="text-2xl font-bold text-gray-900 sm:text-3xl">Orders</h2>
        <select
          className="rounded-xl border border-gray-300 px-3 py-2 text-sm"
          value={statusFilter}
          onChange={(e) => setStatusFilter(e.target.value)}
        >
          <option value="">All statuses</option>
          {statusOptions.map((status) => (
            <option key={status} value={status}>
              {status}
            </option>
          ))}
        </select>
      </div>

      {error ? <div className="rounded-2xl border border-red-200 bg-red-50 p-3 text-red-700">{error}</div> : null}

      <div className="space-y-3">
        {loading ? (
          <div className="rounded-2xl border border-gray-100 bg-white p-6 text-center text-gray-500 shadow-sm">
            Loading orders...
          </div>
        ) : orders.length === 0 ? (
          <div className="rounded-2xl border border-gray-100 bg-white p-6 text-center text-gray-500 shadow-sm">
            No orders found.
          </div>
        ) : (
          orders.map((order) => {
            const displayStatus = order.rejectionReason ? "rejected" : order.status || "pending";
            const latestPaymentStatus = order.latestPayment?.status || "no_payment";
            const receiptAvailable = Boolean(order.latestReceipt);

            return (
              <article key={order.id} className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm sm:p-5">
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div>
                    <p className="font-semibold text-gray-900">{order.id}</p>
                    <p className="mt-0.5 text-xs text-gray-500">
                      Created: {formatDateTime(order.createdAt)}
                    </p>
                  </div>
                  <div className="flex flex-wrap items-center gap-2">
                    <span className={`rounded-full px-3 py-1 text-xs ${statusBadge[displayStatus] || statusBadge.pending}`}>
                      {displayStatus}
                    </span>
                    <span
                      className={`rounded-full px-3 py-1 text-xs ${
                        paymentBadge[latestPaymentStatus] || "bg-gray-100 text-gray-600"
                      }`}
                    >
                      {latestPaymentStatus === "no_payment" ? "no payment" : `payment ${latestPaymentStatus}`}
                    </span>
                  </div>
                </div>

                <div className="mt-4 grid grid-cols-1 gap-3 lg:grid-cols-3">
                  <section className="rounded-xl border border-gray-200 bg-gray-50 p-3">
                    <p className="text-xs font-semibold uppercase tracking-[0.16em] text-gray-500">Customer</p>
                    <div className="mt-2 space-y-1 text-sm text-gray-700">
                      <p>
                        <span className="font-medium">Name:</span> {order.user?.name || "-"}
                      </p>
                      <p>
                        <span className="font-medium">Email:</span> {order.user?.email || "-"}
                      </p>
                      <p>
                        <span className="font-medium">Phone:</span> {order.user?.phone || "-"}
                      </p>
                      <p>
                        <span className="font-medium">Alt Phone:</span> {order.user?.altPhone || "-"}
                      </p>
                    </div>
                  </section>

                  <section className="rounded-xl border border-gray-200 bg-gray-50 p-3 lg:col-span-2">
                    <p className="text-xs font-semibold uppercase tracking-[0.16em] text-gray-500">Delivery</p>
                    <div className="mt-2 space-y-2 text-sm text-gray-700">
                      <p>
                        <span className="font-medium">Location:</span> {order.address || "-"}
                      </p>
                      <p>
                        <span className="font-medium">Instruction:</span> {order.instruction || "-"}
                      </p>
                      {order.user?.addresses?.length ? (
                        <div>
                          <p className="font-medium text-gray-700">Saved addresses:</p>
                          <div className="mt-1 space-y-1">
                            {order.user.addresses.slice(0, 3).map((address) => (
                              <p key={address.id} className="text-xs text-gray-600">
                                {address.isDefault ? "[Default] " : ""}
                                {address.label}: {address.details}
                              </p>
                            ))}
                          </div>
                        </div>
                      ) : null}
                    </div>
                  </section>
                </div>

                <section className="mt-4 rounded-xl border border-gray-200 bg-gray-50 p-3">
                  <p className="text-xs font-semibold uppercase tracking-[0.16em] text-gray-500">Source Businesses</p>
                  <div className="mt-2 text-sm text-gray-700">{renderSourceBusinesses(order)}</div>
                </section>

                <section className="mt-4 rounded-xl border border-gray-200 bg-gray-50 p-3">
                  <div className="flex flex-wrap items-center justify-between gap-2">
                    <p className="text-xs font-semibold uppercase tracking-[0.16em] text-gray-500">Items Ordered</p>
                    <p className="text-sm font-semibold text-gray-700">Total: {formatCurrency(order.total)}</p>
                  </div>

                  <div className="mt-3 overflow-x-auto">
                    <table className="w-full min-w-[560px] text-sm">
                      <thead className="text-gray-500">
                        <tr>
                          <th className="px-2 py-1 text-left">Item</th>
                          <th className="px-2 py-1 text-left">Source</th>
                          <th className="px-2 py-1 text-right">Qty</th>
                          <th className="px-2 py-1 text-right">Price</th>
                          <th className="px-2 py-1 text-right">Line Total</th>
                        </tr>
                      </thead>
                      <tbody>
                        {(order.items || []).map((item) => (
                          <tr key={item.id}>
                            <td className="px-2 py-1.5 font-medium text-gray-800">{item.name}</td>
                            <td className="px-2 py-1.5 text-xs text-gray-600">
                              {item.possibleBusinesses?.length
                                ? item.possibleBusinesses.map((business) => business.name).join(", ")
                                : "Unknown"}
                            </td>
                            <td className="px-2 py-1.5 text-right">{item.qty}</td>
                            <td className="px-2 py-1.5 text-right">{formatCurrency(item.price)}</td>
                            <td className="px-2 py-1.5 text-right font-medium">
                              {formatCurrency(item.price * item.qty)}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </section>

                {order.rejectionReason ? (
                  <section className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">
                    <span className="font-medium">Rejection reason:</span> {order.rejectionReason}
                  </section>
                ) : null}

                <div className="mt-4 flex flex-wrap items-center gap-2">
                  <button
                    type="button"
                    onClick={() => downloadOrderPdf(order)}
                    className="rounded-xl border border-gray-300 bg-white px-3 py-2 text-xs font-semibold text-gray-700 transition hover:border-orange-300 hover:text-orange-700"
                  >
                    Download Order PDF
                  </button>

                  {statusOptions.map((status) => (
                    <button
                      key={status}
                      type="button"
                      onClick={() => updateOrderStatus(order.id, status)}
                      className={`rounded-xl px-3 py-2 text-xs transition ${
                        status === "rejected"
                          ? "bg-red-100 text-red-700 hover:bg-red-200"
                          : "bg-gray-100 text-gray-700 hover:bg-orange-100 hover:text-orange-700"
                      }`}
                    >
                      {status}
                    </button>
                  ))}

                  {displayStatus === "delivered" ? (
                    receiptAvailable ? (
                      <button
                        type="button"
                        onClick={() => viewReceipt(order)}
                        disabled={viewingReceiptId === order.id}
                        className="rounded-xl bg-blue-100 px-3 py-2 text-xs text-blue-700 transition hover:bg-blue-200 hover:text-blue-800 disabled:opacity-60"
                      >
                        {viewingReceiptId === order.id ? "Opening..." : "View Receipt"}
                      </button>
                    ) : (
                      <button
                        type="button"
                        onClick={() => generateReceipt(order.id)}
                        disabled={generatingReceiptId === order.id}
                        className="rounded-xl bg-green-100 px-3 py-2 text-xs text-green-700 transition hover:bg-green-200 hover:text-green-800 disabled:opacity-60"
                      >
                        {generatingReceiptId === order.id ? "Generating..." : "Generate Receipt"}
                      </button>
                    )
                  ) : null}

                  {order.latestPayment?.receiptUrl ? (
                    <a
                      href={toPublicAssetUrl(order.latestPayment.receiptUrl)}
                      target="_blank"
                      rel="noreferrer"
                      className="rounded-xl border border-gray-300 bg-white px-3 py-2 text-xs text-gray-700 transition hover:border-orange-300 hover:text-orange-700"
                    >
                      View Uploaded Payment Proof
                    </a>
                  ) : null}
                </div>
              </article>
            );
          })
        )}
      </div>

      {selectedReceipt ? <ReceiptModal receipt={selectedReceipt} onClose={() => setSelectedReceipt(null)} /> : null}

      {rejectingOrder ? (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 px-4">
          <div className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl">
            <div className="flex items-start justify-between gap-3">
              <div>
                <h3 className="text-lg font-semibold text-gray-900">Reject order</h3>
                <p className="mt-1 text-sm text-gray-500">
                  Tell the customer why order {rejectingOrder.id} was rejected.
                </p>
              </div>
              <button
                type="button"
                onClick={() => {
                  setRejectingOrder(null);
                  setRejectionReason("");
                }}
                className="text-sm text-gray-500 hover:text-gray-700"
              >
                Close
              </button>
            </div>

            <label className="mt-4 block">
              <span className="text-sm font-medium text-gray-700">Reason</span>
              <textarea
                value={rejectionReason}
                onChange={(e) => setRejectionReason(e.target.value)}
                rows={4}
                className="mt-2 w-full rounded-xl border border-gray-300 px-3 py-2 text-sm outline-none focus:border-orange-500"
                placeholder="For example: customer address could not be confirmed."
              />
            </label>

            <div className="mt-5 flex items-center justify-end gap-2">
              <button
                type="button"
                onClick={() => {
                  setRejectingOrder(null);
                  setRejectionReason("");
                }}
                className="rounded-xl border border-gray-300 px-4 py-2 text-sm text-gray-700 hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={submitRejection}
                className="rounded-xl bg-red-600 px-4 py-2 text-sm text-white hover:bg-red-700"
              >
                Reject order
              </button>
            </div>
          </div>
        </div>
      ) : null}
    </section>
  );
}
